- block:
    - name: Install EPEL
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present

    - name: Install Base Packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - python-pip
        - python-devel
        - sshpass
        - gcc
        - libffi-devel
        - openssl-devel
        - vim

    - name: Install Ansible via PIP
      pip:
        name: ansible
        state: present

    - name: Upgrade setuptools via PIP
      pip:
        name: setuptools
        state: latest
  when: install_ansible

- name: Install packages on control
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - git

- name: Create ssh dir
  file:
    state: directory
    path: /home/{{ username }}/.ssh
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: o-rwx

- name: Clone lightbulb
  git:
    accept_hostkey: yes
    clone: yes
    dest: /home/{{ username }}/lightbulb
    repo: https://github.com/gdykeman/ansible-lightbulb
    force: yes

- name: Update Perms for Git Clone
  file:
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    path: /home/{{ username }}/lightbulb

- name: Remove things that students don't need
  file:
    state: absent
    path: /home/{{ username }}/lightbulb/{{ item }}
  with_items:
    - aws_lab_setup
    - resources
    - Vagrantfile
    - README.md

- name: Install AWS ansible.cfg in home directory
  copy:
    src: ansible.cfg
    dest: /home/{{ username }}/.ansible.cfg
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create lab inventory directory
  file:
    state: directory
    path: /home/{{ username }}/lightbulb/lessons/lab_inventory

#- name: Setup student inventory in proper spot
#  copy:
#    src: ./instances/{{ username }}-instances.txt
#    dest: /home/{{ username }}/lightbulb/lessons/lab_inventory/hosts
#  when: "username in inventory_hostname"

- name: Setup student inventory in proper spot
  copy:
    src: ./instances/{{ username }}-instances.txt
    dest: /home/{{ username }}/lightbulb/inventory
  when: "username in inventory_hostname"

- name: Update Perms from home dir down
  file:
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    path: /home/{{ username }}
