---
- name: stop services to re-run playbooks
  hosts: web
  become: yes

  tasks:
    - name: stop httpd and nginx
      service:
         name: {{ item }}
         state: stopped
      ignore_errors: yes
      with_items:
        - httpd
        - nginx
